modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="new_enchantments_mod"
version="1.0.0"
displayName="New Enchantments Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Francesco, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.new_enchantments_mod]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.new_enchantments_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.new_enchantments_mod]]
    modId="mcreator_link"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.new_enchantments_mod]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

